### ISSUE TITLE
makeCombinedREADME not working correctly on macOS

### ISSUE THREAD

**Issue by philipcardiff** [solids4foam/solid-benchmarks#14]
The makeCombinedREADME script does not work correctly on macOS. It uses more and more memory until the OS complains; it also generates a huge (> 100 GB) combined file.

**Comment by iBatistic** [comment]
I tried it on Ubuntu and it worked, I will check this further.

**Comment by philipcardiff** [comment]
> I tried it on Ubuntu and it worked, I will check this further.

I think this is a problem with pandoc, but I am not sure why. It is not a major issue as I have not really used this combined README, but it is useful to keep this issue here to let others know.

**Comment by philipcardiff** [comment]
Resolved in https://github.com/solids4foam/solid-benchmarks/pull/15

**Comment by iBatistic** [comment]
> I think this is a problem with pandoc, but I am not sure why. It is not a major issue as I have not really used this combined README, but it is useful to keep this issue here to let others know.

True, the script is not very useful, but sometimes it might be needed (for example, check if everything is consistent across README files). Remaining problem is that Pandoc treats $ and $$ differently, so the generated html is chaotic.
